In [2]:
import numpy as np

In [3]:
x = np.array([[1],[2],[3]])

In [4]:
x.shape

(3, 1)

In [6]:
print(f'A 3-D vactor: \n{x}')

A 3-D vactor: 
[[1]
 [2]
 [3]]


In [11]:
y = np.array([[1],[2],[4]])

In [12]:
y.shape

(3, 1)

In [14]:
x + y

array([[2],
       [4],
       [7]])

In [15]:
alpha = 2
alpha * y

array([[2],
       [4],
       [8]])

In [16]:
np.multiply(alpha, y)

array([[2],
       [4],
       [8]])

In [17]:
a, b = 2, 3
x, y = np.array([[2],[3]]), np.array([[4],[5]])

In [20]:
a*x + b*y   # linear multiplication

array([[16],
       [21]])

In [23]:
# Dot product - > @
x.T@y

array([[23]])

In [24]:
# Vector Norms
# 1. Euclidean norm

x = np.array([[3],[4]])
np.linalg.norm(x, 2)

5.0

In [25]:
# 2. Manhattan norm

x = np.array([[3],[-4]])
np.linalg.norm(x, 1)

7.0

In [26]:
# 3. Max norm

x = np.array([[3],[-4]])
np.linalg.norm(x, np.inf)

4.0

In [29]:
# Distance of two vector
x, y = np.array([[-2],[2]]), np.array([[4],[-3]])
distance = np.linalg.norm(x-y, 2)
print(distance)

7.810249675906656


In [37]:
# Angle between two vector

x, y = np.array([[1],[-2]]), np.array([[5],[7]])
cos_theta = (x.T @ y) / (np.linalg.norm(x, 2) *  np.linalg.norm(y, 2))
cos_theta

array([[-0.46788772]])

In [38]:
np.round(cos_theta, 3)

array([[-0.468]])

In [40]:
cos_inverse = np.arccos(cos_theta)
cos_inverse

array([[2.05769556]])

In [41]:
degree = cos_inverse * ((180)/np.pi)
degree

array([[117.89727103]])

In [44]:
x, y = np.array([[2],[0]]), np.array([[0],[2]])
cos_theta = (x.T @ y) / (np.linalg.norm(x, 2) *  np.linalg.norm(y, 2))
cos_theta
np.round(cos_theta, 3)
cos_inverse = np.arccos(cos_theta)
cos_inverse
degree = cos_inverse * ((180)/np.pi)
degree

array([[90.]])