In [3]:
import numpy as np

In [2]:
# System of linaer equaltions
# x + 2y = 8
# 5x - 3y = 1

In [4]:
A = np.array([[0,2],   # 1st row
              [1,4]])  # 2nd row
print(A)

[[0 2]
 [1 4]]


In [5]:
A.shape

(2, 2)

In [6]:
B = np.array([[3,1],   # 1st row
              [-3,2]])  # 2nd row
print(B)

[[ 3  1]
 [-3  2]]


In [7]:
print(A+B)

[[ 3  3]
 [-2  6]]


In [8]:
mat_sum = A + B
mat_sum

array([[ 3,  3],
       [-2,  6]])

In [9]:
np.add(A, B)

array([[ 3,  3],
       [-2,  6]])

In [13]:
C = np.array([[0,2,4],   # 1st row
              [1,4,2],   # 2nd row
              [5,6,8]])  # 3rd row
print(C)

[[0 2 4]
 [1 4 2]
 [5 6 8]]


In [15]:
# Matrix-scalar multiplication
alpha = 2
mat_scalar_mul = alpha * mat_sum
mat_scalar_mul

array([[ 6,  6],
       [-4, 12]])

In [16]:
# Matrix-vector multiplication
x = np.array([[1],
              [2]])
A @ x

array([[4],
       [9]])

In [17]:
np.dot(A, x)

array([[4],
       [9]])

In [19]:
D = np.array([[1],
              [2]])
E = np.array([[5],
              [8]])
# np.dot(D, E)   # error
np.dot(D.T, E)

array([[21]])

In [20]:
# Matrix-matrix multiplication
A @ B

array([[-6,  4],
       [-9,  9]])

In [21]:
# Matrix-Inverse
F = np.array([[1,2,1],
              [4,4,5],
              [6,7,7]])
F_inverse = np.linalg.inv(F)
print(F_inverse)

[[-7. -7.  6.]
 [ 2.  1. -1.]
 [ 4.  5. -4.]]


In [25]:
I = F_inverse @ F
np.round(I)

array([[ 1.,  0.,  0.],
       [ 0.,  1., -0.],
       [ 0., -0.,  1.]])

In [29]:
# Matrix Transpose
G = np.array([[1,2],
             [3,4],
             [5,6]])
G.shape

(3, 2)

In [33]:
mat_transpose = G.T
mat_transpose

array([[1, 3, 5],
       [2, 4, 6]])

In [31]:
mat_transpose.shape

(2, 3)

In [34]:
# Hadamard product
B = A = np.array([[0,2],    # 1st row
                  [1,4]])   # 2nd row
A * B

array([[ 0,  4],
       [ 1, 16]])

In [35]:
np.multiply(A, B)

array([[ 0,  4],
       [ 1, 16]])

In [ ]:
# Gaussian elimination Method
# 1. addition and subtraction of two equations
# 2. Multiplication of an equation by a number
# 3. Switching an equation

In [37]:
M = np.array([[1,3,5],
              [2,2,-1],
              [1,3,2]])
y = np.array([[-1],
              [1],
              [2]])
print(y)

[[-1]
 [ 1]
 [ 2]]


In [38]:
solution = np.linalg.solve(M, y)
solution

array([[-2.],
       [ 2.],
       [-1.]])

In [ ]:
# A set of n Linaerly indepent column vectors with n elements forms a basis
