In [1]:
import numpy as np

In [2]:
my_list = [1,2,3,4,5]
my_arr = np.array(my_list)    #np.array(<list>): Used to convert a list into n dimension array

In [3]:
my_arr

array([1, 2, 3, 4, 5])

In [4]:
myarr = np.array([[1,2,3,4]])

In [5]:
myarr

array([[1, 2, 3, 4]])

In [6]:
myarr.shape

(1, 4)

In [7]:
myarr.dtype

dtype('int32')

In [8]:
myarr[0,2]

3

In [9]:
myarr[0,2] = 55

In [10]:
myarr[0,2]

55

# Array Creation

In [11]:
listarray = np.array([[1,2,3], [4,5,6], [7,8,9]]) 

In [12]:
listarray

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
listarray.dtype

dtype('int32')

In [14]:
listarray.shape

(3, 3)

In [15]:
listarray.size

9

In [16]:
zeros = np.zeros((2, 5))

In [17]:
zeros

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [18]:
zeros.dtype

dtype('float64')

In [19]:
rng = np.arange(15)

In [20]:
rng

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [21]:
lspace = np.linspace(1,5,4)

In [22]:
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [23]:
emp = np.empty((2,3))

In [24]:
emp

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306],
       [1.33511018e-306, 6.23054633e-307, 2.22526399e-307]])

In [25]:
#creating a 2d array

my_list1 = [1,2,3,4,5,6,7]
my_list2 = [8,9,10,11,12,13,14]
my_list3 = [15,16,17,18,19,20,21]
my_arr1 = np.array([my_list1,my_list2,my_list3])      

In [26]:
my_arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [27]:
type(my_arr1)

numpy.ndarray

In [28]:
my_arr1.shape

(3, 7)

In [29]:
my_arr1.reshape(7,3)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18],
       [19, 20, 21]])

In [30]:
my_arr1.ravel()           # 1D array

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19, 20, 21])

In [31]:
my_arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [32]:
print(my_arr1[1:,5:])

[[13 14]
 [20 21]]


In [33]:
print(my_arr1[0:3,3:])

[[ 4  5  6  7]
 [11 12 13 14]
 [18 19 20 21]]


In [34]:
my_arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [35]:
my_arr1.sum(axis=0)

array([24, 27, 30, 33, 36, 39, 42])

In [36]:
my_arr1.sum(axis=1)

array([ 28,  77, 126])

In [37]:
my_arr1.T

array([[ 1,  8, 15],
       [ 2,  9, 16],
       [ 3, 10, 17],
       [ 4, 11, 18],
       [ 5, 12, 19],
       [ 6, 13, 20],
       [ 7, 14, 21]])

In [38]:
for items in my_arr1:
    print(items)

[1 2 3 4 5 6 7]
[ 8  9 10 11 12 13 14]
[15 16 17 18 19 20 21]


In [39]:
for items in my_arr1.flat:
    print(items)

1
2
3
4
5
6
7
8
9
10
11
12
13
14
15
16
17
18
19
20
21


In [40]:
my_arr1.ndim

2

In [41]:
my_arr1.nbytes

84

In [42]:
one = np.array([1,3,5,23,4])

In [43]:
one.argmax()

3

In [44]:
one.argmin()

0

In [45]:
one.argsort()

array([0, 1, 4, 2, 3], dtype=int64)

In [46]:
my_arr1

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19, 20, 21]])

In [47]:
my_arr1.argmin()

0

In [48]:
my_arr1.argmax()

20

In [49]:
my_arr1.argsort()

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]], dtype=int64)

In [50]:
my_arr1.argmax(axis=0)

array([2, 2, 2, 2, 2, 2, 2], dtype=int64)

In [51]:
my_arr1.argmax(axis=1)

array([6, 6, 6], dtype=int64)

In [52]:
my_arr1.argsort(axis=1)

array([[0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6],
       [0, 1, 2, 3, 4, 5, 6]], dtype=int64)