In [1]:
import csv

# Data to be written into the CSV file
data = [
["S. No.", "Names", "Years of Experience", "Domain", "Relevant Experience", "Income(USD)", "Marital Status", "Number of siblings", "dummy"],
[1, "John", 8, "Automotive", 6.0, 20000.0, "Single", 3, 0.0],
[2, "Jason", 5, "Entertainment", 4.0, 15000.0, "Married", 3, 0.0],
[3, "Maria", 10, "Banking", 3.0, 18000.0, "Single", 3, 0.0],
[4, "Jacob", 12, "Insurance", 10.0, 24000.0, "Single", 3, 0.0],
[5, "Sarah", 15, "Logistics", 5.0, 8000.0, "Married", 3, 0.0],
[6, "Angelina", 3, "Travel", 3.0, 9500.0, "Married", 3, 0.0],
[7, "Krishna", 0, "NaN", "NaN", "NaN", "Single", 3, 0.0],
[8, "Adam", 8, "Food", 5.0, 7500.0, "Single", 3, 0.0],
[9, "Deepika", 15, "IT", 13.0, 19500.0, "Married", 3, 0.0],
[10, "Alan", 2, "Space", 1.0, 12500.0, "Married", 3, 0.0]
]

# Specify the file name
csv_file = '12data.csv'

# Write data into the CSV file
with open(csv_file, 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(data)

print(f'CSV file "{csv_file}" has been created successfully.')

CSV file "08data.csv" has been created successfully.


In [2]:
import pandas as pd
import numpy as np

In [3]:
# data = pd.read_excel('Sample_sheet.xlsx')
data = pd.read_csv('08data.csv')
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
2       3     Maria                   10        Banking                  3.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  Number of siblings  dummy  
0      20000.0         Single                   3    0.0  
1      15000.0        Married                   3    0.0  
2      18000.0         Single                   3    0.0  
3      24000.0         Single                   3    0.0  
4       8000.0        Married                   3    0.0  
5       9500.0        Married                   3    0.0  
6          NaN         Single                   3    0.0  
7       7500.0         Single                   3    0.0  
8      19500.0        Married                   3    0.0  
9      12500.0        Married                   3    0.0

In [4]:
# Adding a dummy columns of only zeros
# data['zero'] = np.zeros(10)
data['zero'] = np.zeros((len(data)))
# data['zero'] = 0
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
2       3     Maria                   10        Banking                  3.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  Number of siblings  dummy  zero  
0      20000.0         Single                   3    0.0   0.0  
1      15000.0        Married                   3    0.0   0.0  
2      18000.0         Single                   3    0.0   0.0  
3      24000.0         Single                   3    0.0   0.0  
4       8000.0        Married                   3    0.0   0.0  
5       9500.0        Married                   3    0.0   0.0  
6          NaN         Single                   3    0.0   0.0  
7       7500.0         Single                   3    0.0   0.0  
8      19500.0        Married                   3    0.0   0.0  
9      12500.0        Married                   3    0.0   0.0

In [5]:
data.drop('dummy', axis = 1, inplace = True)
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
2       3     Maria                   10        Banking                  3.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  Number of siblings  zero  
0      20000.0         Single                   3   0.0  
1      15000.0        Married                   3   0.0  
2      18000.0         Single                   3   0.0  
3      24000.0         Single                   3   0.0  
4       8000.0        Married                   3   0.0  
5       9500.0        Married                   3   0.0  
6          NaN         Single                   3   0.0  
7       7500.0         Single                   3   0.0  
8      19500.0        Married                   3   0.0  
9      12500.0        Married                   3   0.0

In [6]:
print('Shape of data :',data.shape)

Shape of data : (10, 9)


In [7]:
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
2       3     Maria                   10        Banking                  3.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  Number of siblings  zero  
0      20000.0         Single                   3   0.0  
1      15000.0        Married                   3   0.0  
2      18000.0         Single                   3   0.0  
3      24000.0         Single                   3   0.0  
4       8000.0        Married                   3   0.0  
5       9500.0        Married                   3   0.0  
6          NaN         Single                   3   0.0  
7       7500.0         Single                   3   0.0  
8      19500.0        Married                   3   0.0  
9      12500.0        Married                   3   0.0

In [8]:
print('Data types: \n', data.dtypes)

Data types: 
 S. No.                   int64
Names                   object
Years of Experience      int64
Domain                  object
Relevant Experience    float64
Income(USD)            float64
Marital Status          object
Number of siblings       int64
zero                   float64
dtype: object


In [9]:
data.drop('Number of siblings', axis = 1, inplace = True)

In [10]:
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
2       3     Maria                   10        Banking                  3.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  zero  
0      20000.0         Single   0.0  
1      15000.0        Married   0.0  
2      18000.0         Single   0.0  
3      24000.0         Single   0.0  
4       8000.0        Married   0.0  
5       9500.0        Married   0.0  
6          NaN         Single   0.0  
7       7500.0         Single   0.0  
8      19500.0        Married   0.0  
9      12500.0        Married   0.0

In [11]:
# Drop the row
data.drop(2)

# use this to permanently drop
data.drop(2, inplace = True)

In [12]:
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  zero  
0      20000.0         Single   0.0  
1      15000.0        Married   0.0  
3      24000.0         Single   0.0  
4       8000.0        Married   0.0  
5       9500.0        Married   0.0  
6          NaN         Single   0.0  
7       7500.0         Single   0.0  
8      19500.0        Married   0.0  
9      12500.0        Married   0.0

In [13]:
# List all values and unique values
print('All the values :',data['Years of Experience'].values)
print('All the unique values :',data['Years of Experience'].unique())

All the values : [ 8  5 12 15  3  0  8 15  2]
All the unique values : [ 8  5 12 15  3  0  2]


In [14]:
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  zero  
0      20000.0         Single   0.0  
1      15000.0        Married   0.0  
3      24000.0         Single   0.0  
4       8000.0        Married   0.0  
5       9500.0        Married   0.0  
6          NaN         Single   0.0  
7       7500.0         Single   0.0  
8      19500.0        Married   0.0  
9      12500.0        Married   0.0

In [15]:
# Detection of missing values

data.isna().any()

S. No.                 False
Names                  False
Years of Experience    False
Domain                  True
Relevant Experience     True
Income(USD)             True
Marital Status         False
zero                   False
dtype: bool

In [16]:
# Number of missing values across columns
data_ = data.isna()
data_

S. No.  Names  Years of Experience  Domain  Relevant Experience  \
0   False  False                False   False                False   
1   False  False                False   False                False   
3   False  False                False   False                False   
4   False  False                False   False                False   
5   False  False                False   False                False   
6   False  False                False    True                 True   
7   False  False                False   False                False   
8   False  False                False   False                False   
9   False  False                False   False                False   

   Income(USD)  Marital Status   zero  
0        False           False  False  
1        False           False  False  
3        False           False  False  
4        False           False  False  
5        False           False  False  
6         True           False  False  
7        False           False  False  
8        False           False  False  
9        False           False  False

In [17]:
# Treatment of missing values
# Using a constant value
data['Domain'].fillna('Government')

0       Automotive
1    Entertainment
3        Insurance
4        Logistics
5           Travel
6       Government
7             Food
8               IT
9            Space
Name: Domain, dtype: object

In [18]:
data['Income(USD)'].fillna(3000)

0    20000.0
1    15000.0
3    24000.0
4     8000.0
5     9500.0
6     3000.0
7     7500.0
8    19500.0
9    12500.0
Name: Income(USD), dtype: float64

In [19]:
#Using a mean of the series

data['Income(USD)'].fillna(data['Income(USD)'].mean())

0    20000.0
1    15000.0
3    24000.0
4     8000.0
5     9500.0
6    14500.0
7     7500.0
8    19500.0
9    12500.0
Name: Income(USD), dtype: float64

In [20]:
#Using a median of the series

data['Income(USD)'].fillna(data['Income(USD)'].median())

0    20000.0
1    15000.0
3    24000.0
4     8000.0
5     9500.0
6    13750.0
7     7500.0
8    19500.0
9    12500.0
Name: Income(USD), dtype: float64

In [21]:
from sklearn.impute import SimpleImputer
imp_constant = SimpleImputer(strategy='constant', fill_value=1111)
imp_mean = SimpleImputer(strategy='mean')
imp_median = SimpleImputer(strategy='median')
imp_mode = SimpleImputer(strategy='most_frequent')

In [22]:
data[['Income(USD)']]

Income(USD)
0      20000.0
1      15000.0
3      24000.0
4       8000.0
5       9500.0
6          NaN
7       7500.0
8      19500.0
9      12500.0

In [23]:
imp_constant.fit_transform(data[['Income(USD)']])

array([[20000.],
       [15000.],
       [24000.],
       [ 8000.],
       [ 9500.],
       [ 1111.],
       [ 7500.],
       [19500.],
       [12500.]])

In [24]:
imp_mean.fit_transform(data[['Income(USD)']])

array([[20000.],
       [15000.],
       [24000.],
       [ 8000.],
       [ 9500.],
       [14500.],
       [ 7500.],
       [19500.],
       [12500.]])

In [25]:
imp_mean.statistics_

array([14500.])

In [26]:
imp_mean.fit_transform(data[['Relevant Experience']])
imp_mean.statistics_

array([5.875])

In [27]:
imp_median.fit_transform(data[['Income(USD)']])

array([[20000.],
       [15000.],
       [24000.],
       [ 8000.],
       [ 9500.],
       [13750.],
       [ 7500.],
       [19500.],
       [12500.]])

In [28]:
imp_mode.fit_transform(data[['Income(USD)']])

array([[20000.],
       [15000.],
       [24000.],
       [ 8000.],
       [ 9500.],
       [ 7500.],
       [ 7500.],
       [19500.],
       [12500.]])

In [29]:
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  zero  
0      20000.0         Single   0.0  
1      15000.0        Married   0.0  
3      24000.0         Single   0.0  
4       8000.0        Married   0.0  
5       9500.0        Married   0.0  
6          NaN         Single   0.0  
7       7500.0         Single   0.0  
8      19500.0        Married   0.0  
9      12500.0        Married   0.0

In [30]:
# Permanent replacement of missing values
data['Income(USD)'] = imp_mode.fit_transform(data[['Income(USD)']])
data

S. No.     Names  Years of Experience         Domain  Relevant Experience  \
0       1      John                    8     Automotive                  6.0   
1       2     Jason                    5  Entertainment                  4.0   
3       4     Jacob                   12      Insurance                 10.0   
4       5     Sarah                   15      Logistics                  5.0   
5       6  Angelina                    3         Travel                  3.0   
6       7   Krishna                    0            NaN                  NaN   
7       8      Adam                    8           Food                  5.0   
8       9   Deepika                   15             IT                 13.0   
9      10      Alan                    2          Space                  1.0   

   Income(USD) Marital Status  zero  
0      20000.0         Single   0.0  
1      15000.0        Married   0.0  
3      24000.0         Single   0.0  
4       8000.0        Married   0.0  
5       9500.0        Married   0.0  
6       7500.0         Single   0.0  
7       7500.0         Single   0.0  
8      19500.0        Married   0.0  
9      12500.0        Married   0.0

In [31]:
# Row with the missing values
data[data['Domain'].isna()]

S. No.    Names  Years of Experience Domain  Relevant Experience  \
6       7  Krishna                    0    NaN                  NaN   

   Income(USD) Marital Status  zero  
6       7500.0         Single   0.0