In [6]:
distance = [10, 15, 17, 26]
time = [0.3, 0.47, 0.55, 1.20]

In [7]:
speed = distance/time

TypeError: unsupported operand type(s) for /: 'list' and 'list'

In [8]:
import numpy as np

In [9]:
np_distance = np.array(distance)
np_time = np.array(time)

In [10]:
np_speed = np_distance/np_time

In [13]:
np_speed

array([33.33333333, 31.91489362, 30.90909091, 21.66666667])

In [15]:
#Classes and attributes of ndarray
np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])

In [16]:
np_city.ndim

1

In [17]:
np_city_with_state = np.array([['NYC', 'LA', 'Miami', 'Houston'], 
                               ['NY', 'CA', 'FA', 'TX']])
np_city_with_state

array([['NYC', 'LA', 'Miami', 'Houston'],
       ['NY', 'CA', 'FA', 'TX']], dtype='<U7')

In [18]:
np_city_with_state.ndim

2

In [19]:
np_city.shape

(4,)

In [20]:
np_city_with_state.shape

(2, 4)

In [ ]:
#Shape, size, ndim and dtype are attributes of ndarray

In [ ]:
#Basic operations on an array

In [21]:
first_trail_cyclist = [10, 15, 17, 26]
second_trail_cyclist = [12, 11, 21, 24]

In [22]:
np_first_trail_cyclist = np.array(first_trail_cyclist)
np_second_trail_cyclist = np.array(second_trail_cyclist)

In [26]:
total_distance = np_first_trail_cyclist + np_second_trail_cyclist
total_distance

array([22, 26, 38, 50])

In [27]:
#Access the array elements
cyclist_trails = np.array([[10, 15, 17, 26], [12, 11, 21, 24]])

cyclist_trails.shape

(2, 4)

In [28]:
first_trail = cyclist_trails[0]
first_trail

array([10, 15, 17, 26])

In [29]:
second_trail = cyclist_trails[1]
second_trail

array([12, 11, 21, 24])

In [32]:
fisrt_cyclist_all_trails = cyclist_trails[:,0]
fisrt_cyclist_all_trails

array([10, 12])

In [33]:
cyclist_trails

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [34]:
two_cyclist_trails_data = cyclist_trails[:, 0:2]

In [35]:
two_cyclist_trails_data

array([[10, 15],
       [12, 11]])

In [36]:
#Accessing array elements: iterations
for i in cyclist_trails:
    print(i)

[10 15 17 26]
[12 11 21 24]


In [37]:
for j in two_cyclist_trails_data:
    print(j)

[10 15]
[12 11]


In [38]:
#Indexing with boolean arrays
test_scores =  np.array([[83, 71, 57, 63], [54, 68, 81, 45]])

In [39]:
pass_score = test_scores > 60

In [40]:
print(pass_score)

[[ True  True False  True]
 [False  True  True False]]


In [43]:
test_scores[pass_score]

array([83, 71, 63, 68, 81])

In [44]:
#Copy and views
#Simple assignment
np_city = np.array(['NYC', 'LA', 'Miami', 'Houston'])

In [45]:
np_city #Original

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [46]:
new_np_city = np_city

In [47]:
new_np_city #Assigned data

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [48]:
new_np_city is np_city

True

In [49]:
#View or shallow copy
new_np_city

array(['NYC', 'LA', 'Miami', 'Houston'], dtype='<U7')

In [50]:
view_of_new_np_city = new_np_city.view()

In [51]:
len(view_of_new_np_city)

4

In [52]:
view_of_new_np_city[3] = 'Central'

In [53]:
view_of_new_np_city

array(['NYC', 'LA', 'Miami', 'Central'], dtype='<U7')

In [54]:
new_np_city is view_of_new_np_city

False

In [56]:
new_np_city

array(['NYC', 'LA', 'Miami', 'Central'], dtype='<U7')

In [57]:
#Deep copy
copy_of_new_np_city = new_np_city.copy()

In [58]:
copy_of_new_np_city is new_np_city

False

In [59]:
copy_of_new_np_city[2] = 'LPU'

In [60]:
new_np_city

array(['NYC', 'LA', 'Miami', 'Central'], dtype='<U7')

In [61]:
copy_of_new_np_city

array(['NYC', 'LA', 'LPU', 'Central'], dtype='<U7')

In [64]:
#Ufunc
#sqrt, cos, floor, exp
np_sqrt = np.sqrt([16, 4, 9])
#print(np_distance)
print(np_sqrt.astype(int))

[4 2 3]


In [65]:
np.cos(0)

1.0

In [69]:
from numpy import pi

In [70]:
np.sin(pi/2)

1.0

In [71]:
np.cos(pi)

-1.0

In [73]:
np.floor([1.5, 2.6, 3.6]).astype(int)

array([1, 2, 3])

In [74]:
np.exp([0, 1, 2])

array([1.        , 2.71828183, 7.3890561 ])

In [ ]:
#Shape Manipulation
#ravel, Split, flatten, resize, reshape, stack

In [76]:
cyclist_trails

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [79]:
#Falttening of array
new_oneD_array = cyclist_trails.flatten()
new_oneD_array

array([10, 15, 17, 26, 12, 11, 21, 24])

In [80]:
new_oneD_array.ndim

1

In [84]:
new_oneD_array.reshape(2, 4)

array([[10, 15, 17, 26],
       [12, 11, 21, 24]])

In [98]:
a, b = np.hsplit(new_oneD_array, 2)

In [90]:
np.hstack((new_oneD_array, new_oneD_array))

array([10, 15, 17, 26, 12, 11, 21, 24, 10, 15, 17, 26, 12, 11, 21, 24])

In [96]:
a

array([10, 15, 17, 26])

In [97]:
b

array([12, 11, 21, 24])

In [99]:
a + b

array([22, 26, 38, 50])

In [94]:
d

array([21, 24])